/** UI-04 copy belongs to presentation; it never implies a new runtime state. */
export const CANDIDATE_WORKSPACE_COPY = {
  en: {
    summary: "Candidate summary", detected: "Detected", selected: "Selected", solved: "Solved", risky: "Risky",
    actions: "Candidate actions", currentView: "Current View", fullPage: "Full Page", solveFill: "Solve & Fill",
    stop: "Stop Solve & Fill", cancelScan: "Cancel scan", solveSelected: "Solve selected", fillSelected: "Fill selected",
    retryReview: "Retry review items", selectReview: "Select review items", clear: "Clear selection",
    filters: "Filter candidates", all: "All", unsolved: "Unsolved", review: "Review",
    question: (index: number) => `Question ${index}`, select: (index: number) => `Select question ${index}`,
    blank: (index: number) => `Blank ${index}`,
    status: { detected: "Detected", solving: "Solving", solved: "Solved", review: "Review", failed: "Failed", stale: "Page changed" },
    locate: "Locate", figure: "Question figure", imageUnavailable: "This question contains an image, but its preview is unavailable. Inspect it on the page.",
    noPreview: "No question preview available.", answer: "Answer", confidence: "Confidence", lowConfidence: "Low answer confidence. Review before filling.",
    incomplete: "The result contains incomplete-question hints. Check the question and options on the page.",
    failedReview: "This question could not be solved. Review it before retrying.",
    fill: "Fill answer", fillUnavailable: "Fill unavailable", unverified: "The result source is unverified; filling is unavailable.",
    extractionFailed: "A safe structured answer could not be extracted; filling is unavailable.",
    retryVision: "Retry with Vision", showDetails: "View explanation", hideDetails: "Hide explanation",
    showQuestion: "Show full question", hideQuestion: "Collapse question",
    notStarted: 'Use "Current View" or "Full Page" to start detection.', completedEmpty: "Scan completed, but no usable questions were recognized. Check page loading or try Current View.",
    failedEmpty: "The scan failed; this is not evidence that the page has no questions. Please retry.",
    incompleteEmpty: "Questions were detected but lost during refinement. Try Current View and review the page.",
    filteredCandidateEmpty: "Potential questions were observed but rejected by the initial candidate filter. Try Current View or inspect the page.",
    postprocessedEmpty: "Candidates were retained during scanning but removed by postprocessing. Try Current View and inspect the page.",
    detectingEmpty: "Detecting questions…", filterEmpty: "No questions match this filter.",
  },
  zh: {
    summary: "候选题目概览", detected: "已识别", selected: "已选中", solved: "已完成", risky: "待复核",
    actions: "候选题目操作", currentView: "当前屏", fullPage: "整页扫描", solveFill: "解析并填答",
    stop: "停止解析并填答", cancelScan: "取消扫描", solveSelected: "解析所选", fillSelected: "填写所选",
    retryReview: "重试待复核题目", selectReview: "选择待复核题目", clear: "清除选择",
    filters: "筛选候选题目", all: "全部", unsolved: "待解析", review: "待复核",
    question: (index: number) => `第 ${index} 题`, select: (index: number) => `选择第 ${index} 题`,
    blank: (index: number) => `第 ${index} 空`,
    status: { detected: "已识别", solving: "解析中", solved: "已完成", review: "待复核", failed: "失败", stale: "页面已变化" },
    locate: "定位", figure: "题目配图", imageUnavailable: "该题包含图片，但当前无法预览。请在原页面查看。",
    noPreview: "暂无题目预览。", answer: "答案", confidence: "置信度", lowConfidence: "答案置信度较低，请先复核再填写。",
    incomplete: "解析结果包含题目信息不完整的线索，请在原页面核对题干和选项。",
    failedReview: "该题解析失败，请检查题目后重试。",
    fill: "填写答案", fillUnavailable: "暂不可填写", unverified: "结果来源未经验证，暂不可填写。",
    extractionFailed: "未提取到可安全填写的结构化答案，暂不可填写。",
    retryVision: "视觉重试", showDetails: "查看解析", hideDetails: "收起解析",
    showQuestion: "展开完整题干", hideQuestion: "收起题干",
    notStarted: "先用“当前屏”或“整页扫描”开始识别。", completedEmpty: "扫描已完成，但未识别到可用题目；可能是页面未加载完成或网站结构暂不兼容。",
    failedEmpty: "扫描过程中发生错误，未能完成识别；不能据此判断页面没有题目，请重试。",
    incompleteEmpty: "扫描曾发现候选，但精修阶段未保留题目。请尝试“当前屏”识别并检查原页面。",
    filteredCandidateEmpty: "页面曾出现候选题目，但初筛未能保留。请尝试“当前屏”识别并检查原页面。",
    postprocessedEmpty: "扫描曾保留候选题目，但后处理未能保留。请尝试“当前屏”识别并检查原页面。",
    detectingEmpty: "正在识别题目…", filterEmpty: "当前筛选条件下没有题目。",
  },
} as const;
