import type { UILang } from "./displayUtils";

export type SetupStatusType =
  | "not_configured"
  | "incomplete"
  | "saved_untested"
  | "testing"
  | "validated"
  | "error";

export const SETTINGS_COPY = {
  zh: {
    status: {
      not_configured: "未配置 AI 服务",
      incomplete: "配置未完成",
      saved_untested: "已保存（待测试）",
      testing: "正在测试配置...",
      validated: "AI 配置已就绪",
      error: "连接测试失败",
    },
    stepper: {
      title: "快速配置引导",
      step1: "选择服务商",
      step2: "凭据模型",
      step3: "测试配置",
      step4: "就绪解题",
      summaryUnconfigured: "请先选择一个 AI 服务商并填写对应的 API Key。",
      summaryIncomplete: "服务商已选定，请继续填写 API Key 并选择模型。",
      summarySavedUntested: "配置已保存，请点击「测试配置」验证是否可用。",
      summaryTesting: "正在向服务商发送轻量测试请求，请稍候...",
      summaryValidated: "配置已验证成功！你可以直接切换到候选题工作台开始使用。",
      summaryError: "连接测试未通过，请检查 API Key、模型或网络设置。",
    },
    readyBanner: {
      badge: "AI 运行正常",
      title: "AI 配置已就绪",
      description: "当前服务商与模型已通过连接验证，可以在候选题工作台开始题目识别与解析。",
      retest: "重新测试",
    },
    provider: {
      title: "服务商",
      description: "选择解析时使用的模型服务商。",
      supportsVision: "支持图像",
      textOnly: "仅文本",
      local: "本地服务",
      keyOptional: "无需 Key",
      keyRequired: "需要 API Key",
      keyOptionalBadge: "Key 可选",
      selected: "当前选中",
      switchHint: "点击切换服务商",
    },
    credentials: {
      titleKey: "API Key",
      titleKeyRequired: "API Key *",
      descRequired: "此服务商需要 API Key 才能进行真实解析。",
      descOptional: "此服务商可以不填写 API Key。",
      emptyHint: "尚未填写 API Key。配置后才能进行 AI 解析和连接测试。",
      localHint: "Ollama 为本地运行服务，通常不需要填写 API Key。",
      showKey: "显示 API Key",
      hideKey: "隐藏 API Key",
      getKeyLink: (platform: string) => `前往 ${platform} 获取 Key`,
      maskedNotice: "API Key 会加密保存在本地，并仅用于向你选择的模型服务商或自定义端点发起请求。",
    },
    model: {
      title: "模型",
      description: "选择预设模型，或手动输入名称。",
      presetSelect: "选择预设模型",
      customModelInput: "输入模型名，例如 gpt-5.4-mini",
      customInputPrompt: "手动输入自定义模型",
      usePresetPrompt: "使用官方预设模型",
    },
    baseUrl: {
      title: "Base URL",
      description: "可选，用于代理或自托管端点。",
      hint: "留空则使用服务商默认地址。",
      ollamaDefaultHint: "Ollama 默认本地端口为 http://localhost:11434",
      invalidUrl: "请输入以 http:// 或 https:// 开头的有效网址",
    },
    advanced: {
      sectionTitle: "高级设置",
      sectionDesc: "自托管端点、协议格式、解析路由及隐私统计",
      customProtocolTitle: "自定义协议",
      customProtocolDesc: "选择你的接口所兼容的 API 格式。",
      protocolOpenAi: "OpenAI 兼容",
      protocolClaude: "Claude 兼容",
      routeTitle: "解析路由",
      routeDesc: "自动模式更稳，只有明确知道页面特征时再强制文本或视觉。",
      routeAuto: "自动",
      routeText: "文本优先",
      routeVision: "视觉优先",
      analyticsBackendTitle: "统计后端",
      analyticsBackendDesc: "账号注册和登录服务使用此后端。",
      deviceIdPrefix: "设备 ID：",
      loading: "加载中...",
      usageTitle: "使用情况统计",
      usageDesc:
        "默认关闭。开启后会发送经过最小化处理的使用事件，例如功能使用、解析成功或失败类别和耗时；不会发送题目内容、答案、网页域名、截图、API Key、账号密码或验证码。关闭统计不会影响账号登录或 AI 解析功能。",
      usageCheckboxAria: "开启可选使用情况统计",
      usageEnabled: "发送最小化的可选使用统计",
      usageDisabled: "不发送可选的使用情况统计",
    },
    language: {
      title: "界面语言",
      description: "Popup 和 Side Panel 都会全局跟随这个设置。",
      zh: "中文",
      en: "English",
    },
    actions: {
      save: "保存设置",
      saved: "已保存",
      unsavedChanges: "有未保存的修改",
      test: "测试配置",
      testAlias: "连接测试",
      testing: "测试中...",
      saveAndTest: "保存并测试",
    },
  },
  en: {
    status: {
      not_configured: "AI Provider Not Configured",
      incomplete: "Configuration Incomplete",
      saved_untested: "Saved (Untested)",
      testing: "Testing Connection...",
      validated: "AI Configuration Ready",
      error: "Connection Test Failed",
    },
    stepper: {
      title: "Setup Guide",
      step1: "Choose Provider",
      step2: "Credentials",
      step3: "Test Setup",
      step4: "Ready",
      summaryUnconfigured: "Please select an AI provider and enter your API Key to get started.",
      summaryIncomplete: "Provider selected. Please enter your API Key and choose a model.",
      summarySavedUntested: "Settings saved. Click \"Test configuration\" to verify your connection.",
      summaryTesting: "Sending a lightweight verification request to provider...",
      summaryValidated: "Configuration verified! You can now switch to Candidates tab and start solving.",
      summaryError: "Connection test failed. Check your API key, model, or network configuration.",
    },
    readyBanner: {
      badge: "Active & Verified",
      title: "AI Configuration Ready",
      description: "Your provider and model are verified. You can now detect and solve questions in the workspace.",
      retest: "Re-test",
    },
    provider: {
      title: "Provider",
      description: "Choose the model provider used for parsing.",
      supportsVision: "Supports images",
      textOnly: "Text only",
      local: "Local provider",
      keyOptional: "Key optional",
      keyRequired: "Key required",
      keyOptionalBadge: "Key optional",
      selected: "Selected",
      switchHint: "Click to select provider",
    },
    credentials: {
      titleKey: "API Key",
      titleKeyRequired: "API Key *",
      descRequired: "This provider requires an API key for real AI parsing.",
      descOptional: "This provider can be used without an API key.",
      emptyHint: "No API key is configured yet. Add one before parsing or testing the connection.",
      localHint: "Ollama runs locally and does not typically require an API key.",
      showKey: "Show API key",
      hideKey: "Hide API key",
      getKeyLink: (platform: string) => `Get key from ${platform}`,
      maskedNotice: "Your API Key is encrypted and stored locally, and is only sent to your chosen AI provider or custom endpoint.",
    },
    model: {
      title: "Model",
      description: "Pick a preset model or type one manually.",
      presetSelect: "Select preset model",
      customModelInput: "Enter model name, for example gpt-5.4-mini",
      customInputPrompt: "Enter custom model name",
      usePresetPrompt: "Use provider preset model",
    },
    baseUrl: {
      title: "Base URL",
      description: "Optional proxy or self-hosted endpoint.",
      hint: "Leave empty to use the provider default endpoint.",
      ollamaDefaultHint: "Ollama default local URL is http://localhost:11434",
      invalidUrl: "Please enter a valid URL starting with http:// or https://",
    },
    advanced: {
      sectionTitle: "Advanced Settings",
      sectionDesc: "Endpoints, wire protocol, routing, and analytics",
      customProtocolTitle: "Custom Protocol",
      customProtocolDesc: "Choose the API format exposed by your endpoint.",
      protocolOpenAi: "OpenAI Compatible",
      protocolClaude: "Claude Compatible",
      routeTitle: "Parse Route",
      routeDesc: "Auto is safer. Force text or vision only when you know the page pattern.",
      routeAuto: "Auto",
      routeText: "Text First",
      routeVision: "Vision First",
      analyticsBackendTitle: "Analytics Backend",
      analyticsBackendDesc: "The account service uses this backend for registration and login.",
      deviceIdPrefix: "Device ID: ",
      loading: "loading...",
      usageTitle: "Usage Analytics",
      usageDesc:
        "Off by default. If enabled, minimized usage events such as feature use, parse outcome category, and duration are sent. They exclude question or answer content, page domains, screenshots, API keys, passwords, and verification codes. Turning analytics off does not affect account sign-in or AI parsing.",
      usageCheckboxAria: "Enable optional usage analytics",
      usageEnabled: "Send minimized optional usage analytics",
      usageDisabled: "Do not send optional usage analytics",
    },
    language: {
      title: "Language",
      description: "The popup and side panel follow this setting globally.",
      zh: "中文",
      en: "English",
    },
    actions: {
      save: "Save Settings",
      saved: "Saved",
      unsavedChanges: "Unsaved changes",
      test: "Test configuration",
      testAlias: "Connection Test",
      testing: "Testing...",
      saveAndTest: "Save & Test",
    },
  },
} as const;

export function getSettingsCopy(lang: UILang) {
  return SETTINGS_COPY[lang === "en" ? "en" : "zh"];
}
